services:

  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000"

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 56157469
      POSTGRES_DB: iurd
    ports:
      - "5432:5432"
